name: Destroy Environments

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Destroy Test
        run: make destroy_test

      - name: Destroy Live
        run: make destroy_live
